# ---- Base Node ----
FROM node:18-alpine 

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install -g pnpm

# DATABASE
ARG DATABASE_USER
ARG DATABASE_PASSWORD
ARG DATABASE_PORT
ARG DATABASE_HOST
ARG DATABASE_URL

ENV DATABASE_USER=${DATABASE_USER}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}
ENV DATABASE_PORT=${DATABASE_PORT}
ENV DATABASE_HOST=${DATABASE_HOST}
ENV DATABASE_URL=${DATABASE_URL}
# JWT
ARG JWT_SECRET
ARG JWT_EXPIRES_IN
ARG JWT_RF_SECRET
ARG JWT_RF_EXPIRES_IN

ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
ENV JWT_RF_SECRET=${JWT_RF_SECRET}
ENV JWT_RF_EXPIRES_IN=${JWT_RF_EXPIRES_IN}
# TOSS
ARG TOSS_PAYMENTS_TEST_SECRET_KEY
ARG TOSS_PAYMENTS_SECRET_KEY

ENV TOSS_PAYMENTS_TEST_SECRET_KEY=${TOSS_PAYMENTS_TEST_SECRET_KEY}
ENV TOSS_PAYMENTS_SECRET_KEY=${TOSS_PAYMENTS_SECRET_KEY}
# CLICK
ARG CLICK_ENC_KEY

ENV CLICK_ENC_KEY=${CLICK_ENC_KEY}
# SMTP
ARG SMTP_SERVICE
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_AUTH_USER
ARG SMTP_AUTH_PASS

ENV SMTP_SERVICE=${SMTP_SERVICE}
ENV SMTP_HOST=${SMTP_HOST}
ENV SMTP_PORT=${SMTP_PORT}
ENV SMTP_AUTH_USER=${SMTP_AUTH_USER}
ENV SMTP_AUTH_PASS=${SMTP_AUTH_PASS}

RUN pnpm install 

COPY . .

RUN pnpm build

EXPOSE 3000

CMD [ "node", "dist/src/main"]

# FROM node:18-alpine

# WORKDIR /app

# COPY --from=builder /usr/src/app/dist /app/dist

# EXPOSE 3000

